spring.application.name=notificaciones-service
server.port=8083

spring.datasource.url=jdbc:postgresql://ep-cool-haze-apsft3a7-pooler.c-7.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_2RHU5ODmgqec&sslmode=require&channelBinding=require
spring.datasource.username=neondeb_owner
spring.datasource.password=npg_2RHU5ODmgqec
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true