spring.application.name=notificaciones-service
server.port=8083

#spring.datasource.url=jdbc:postgresql://ep-cool-haze-apsft3a7-pooler.c-7.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_2RHU5ODmgqec&sslmode=require&channelBinding=require
#spring.datasource.username=neondeb_owner
#spring.datasource.password=npg_2RHU5ODmgqec
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/notificaciones_db
spring.datasource.username=postgres
spring.datasource.password=holaMundo
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cristopherbravo13@gmail.com

spring.mail.password=ysfzwktvxalzohoz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

